name: WeRead Browser Sync
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 延长超时时间
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libgbm-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests notion-client webdriver-manager
          
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x16 &
        
      - name: Set display
        run: echo DISPLAY=:99 >> $GITHUB_ENV
        
      - name: Run browser sync
        id: sync
        env:
          DISPLAY: ":99"
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          # 运行脚本并捕获二维码路径
          OUTPUT=$(python browser_sync.py)
          echo "$OUTPUT"
          
          # 检查二维码路径
          if [[ $OUTPUT == *"qr_path"* ]]; then
            QR_PATH=$(echo "$OUTPUT" | grep "::set-output" | cut -d'=' -f4)
            echo "QR_CODE_PATH=$QR_PATH" >> $GITHUB_OUTPUT
          fi
        
      - name: Upload QR code
        if: steps.sync.outputs.QR_CODE_PATH
        uses: actions/upload-artifact@v3
        with:
          name: we-read-qr-code
          path: ${{ steps.sync.outputs.QR_CODE_PATH }}
