name: Test WeRead Cookie
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install requests  # 添加这行安装依赖
      
      - name: Test Cookie
        env:
          WR_COOKIE: ${{ secrets.WR_COOKIE }}
        run: |
          python cookie_test.py
